### ISSUE TITLE
Error running `grunt --tasks`

### ISSUE THREAD

**Issue by chrisnicola** [AppGyver/grunt-steroids#27]
```
grunt -tasks

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.file.exists (/Users/chrisnicola/src/wealthbar-phone/node_modules/grunt/lib/grunt/file.js:381:28)
    at task.loadTasks (/Users/chrisnicola/src/wealthbar-phone/node_modules/grunt/lib/grunt/task.js:371:18)
    at Array.forEach (native)
    at Task.task.init (/Users/chrisnicola/src/wealthbar-phone/node_modules/grunt/lib/grunt/task.js:457:33)
    at Object.grunt.tasks (/Users/chrisnicola/src/wealthbar-phone/node_modules/grunt/lib/grunt.js:120:8)
    at Object.module.exports [as cli] (/Users/chrisnicola/src/wealthbar-phone/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/local/Cellar/nvm/0.24.0/v0.10.37/lib/node_modules/grunt-cli/bin/grunt:45:20)
```

Not sure what the cause of this is, but it is making it impossible for me to debug issues with customizing our build process.

**Comment by chrisnicola** [comment]
This turned out to be an issue with Grunt itself.
